from enum import StrEnum


class AuthErrorCode(StrEnum):
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    REFRESH_EXPIRED = "REFRESH_EXPIRED"
    EMAIL_ALREADY_USED = "EMAIL_ALREADY_USED"
    USER_NOT_FOUND = "USER_NOT_FOUND"


class ReclamationErrorCode(StrEnum):
    RECLAMATION_NOT_FOUND = "RECLAMATION_NOT_FOUND"
    ATTACHMENT_NOT_FOUND = "ATTACHMENT_NOT_FOUND"


class ChatErrorCode(StrEnum):
    CHAT_NOT_FOUND = "CHAT_NOT_FOUND"
    MESSAGE_NOT_FOUND = "MESSAGE_NOT_FOUND"
