RECLAMATIONS_VALIDATOR = {
    "$jsonSchema": {
        "bsonType": "object",
        "required": [
            "userId",
            "userEmail",
            "referenceNumber",
            "subject",
            "description",
            "issueCategory",
            "priority",
            "status",
            "replyAcknowledged",
            "createdAt",
            "updatedAt",
        ],
        "properties": {
            "userId": {"bsonType": "string", "minLength": 1},
            "userEmail": {"bsonType": "string", "pattern": "^.+@.+\\..+$"},
            "referenceNumber": {"bsonType": "string", "pattern": "^REC-"},
            "subject": {"bsonType": "string", "minLength": 3, "maxLength": 160},
            "description": {"bsonType": "string", "minLength": 10, "maxLength": 3000},
            "issueCategory": {
                "enum": ["BUG_TECHNIQUE", "PROBLEME_JURIDIQUE", "ERREUR_REPONSE_CHATBOT", "AUTRE"]
            },
            "customIssueCategory": {"bsonType": ["string", "null"]},
            "priority": {"enum": ["LOW", "NORMAL", "HIGH", "URGENT"]},
            "status": {"enum": ["PENDING", "IN_PROGRESS", "RESOLVED", "FAILED"]},
            "attachmentName": {"bsonType": ["string", "null"]},
            "attachmentPath": {"bsonType": ["string", "null"]},
            "attachmentSize": {"bsonType": ["int", "long", "null"], "maximum": 5242880},
            "attachmentContentType": {"bsonType": ["string", "null"]},
            "adminReply": {"bsonType": ["string", "null"]},
            "adminReplyAt": {"bsonType": ["date", "null"]},
            "repliedByAdminId": {"bsonType": ["string", "null"]},
            "lastAdminActionAt": {"bsonType": ["date", "null"]},
            "lastAdminActorName": {"bsonType": ["string", "null"]},
            "replyAcknowledged": {"bsonType": "bool"},
            "history": {"bsonType": "array"},
            "createdAt": {"bsonType": "date"},
            "updatedAt": {"bsonType": "date"},
            "deletedAt": {"bsonType": ["date", "null"]},
            "deletedByUserId": {"bsonType": ["string", "null"]},
            "firstHandledAt": {"bsonType": ["date", "null"]},
            "takenByAdminId": {"bsonType": ["string", "null"]},
            "takenByAdminName": {"bsonType": ["string", "null"]},
            "slaOverdueNotifiedAt": {"bsonType": ["date", "null"]},
        },
    }
}
